### ISSUE TITLE
Remove default limit

### ISSUE THREAD

**Issue by XedinUnknown** [RebelCode/rcmod-eddbk-services#20]
In resource models that use `get_posts()` or `WP_Query`, defaults are imposed in accord with the [documentation][`get_posts()`]. Some of these defaults don't really make sense.

As such, the default value for `numberposts`, which is an alias of `posts_per_page`, is 5 in WordPress. This leads to a condition-less, limitless `select()` operation retrieving 5 records, where as it should be retrieving all.

In the default parameters, such as [`ServicesSelectResourceModel#_getDefaultWpQueryArgs()`], add the `posts_per_page` key with value `-1`, indicating that there is no limit.

[`get_posts()`]: https://developer.wordpress.org/reference/functions/get_posts/
[`ServicesSelectResourceModel#_getDefaultWpQueryArgs()`]: https://github.com/RebelCode/rcmod-eddbk-services/blob/develop/src/Module/ServicesSelectResourceModel.php#L158

**Comment by mecha** [comment]
Got it! Thanks for taking the time to investigate the cause and identify the related code 👌
