### ISSUE TITLE
Fix Download meta data querying

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-services#9]
## Symptoms

In EDD Bookings, after loading the New Download page, the session lengths shown in the bookings metabox are not empty. They are actually session lengths from another Download (symptom 1).

This also happens when creating a new Download. Saving the session lengths also seems to save them to another Download (symptom 2).

## How to Reproduce

- Create a Download with some session lengths, if one does not already exist.
- Create a new Download.
- Observe symptom 1.
- Add some session lengths to the new Download and save.
- Open the previous Download Edit page
- Observe symptom 2

## Possible Cause

It seems like the meta data querying is broken.

After some investigation, it became apparent that the compiled `WP_Query` args where being incorrectly built. One of array keys is being generated as `"post.id"`. This is a result from an entity field term in the condition with the entity and field being `"post"` and `"id"` respectively.

This is happening because the args builder logic cannot detect that the entity field term is referencing a property of the "post" entity. It is configured to detect these properties from terms with the entity `"service"`.

## Recommended Solution

Modify resource model consumers such that they provide conditions with the correct entity name (`"service"`) in all entity field terms.

**Comment by markzahra** [comment]
Possibly related to https://github.com/orgs/RebelCode/projects/2#card-9860482

**Comment by XedinUnknown** [comment]
This is pretty amazing, because the strictness of the setup allows us to avoid potential issues in the future. Once again, @mecha's CQRS models win.
